[project]
name = "ArknightsUID"
version = "0.0.1"
description = ""
authors = [
    {name = "qwerdvd", email = "2450899274@qq.com"}
]
dependencies = [
    "msgspec>=0.17.0",
    "pydantic>=2.1.1",
    "fastapi>=0.100.1",
]
requires-python = ">=3.11,<4.0"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}

[project.optional-dependencies]
test = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.1",
]

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.282",
    "black>=23.7.0",
    "isort>=5.12.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
skip-string-normalization = true
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
select = ["E", "W", "F", "UP", "C", "T", "PYI", "PT", "Q"]
ignore = ["E402", "C901", "UP037", "Q000"]

line-length = 88
target-version = "py311"
